import { Highlight } from '@tiptap/extension-highlight'
import markdownitMark from 'markdown-it-mark'

export default Highlight.extend({
  addStorage() {
    return {
      markdown: {
        serialize: {
          open: '==',
          close: '==',
        },
        parse: {
          setup(markdownit) {
            console.log('setup', markdownit.use)
            markdownit.use(markdownitMark)
          },
          updateDOM() {
            // here you can update HTML generated by markdown-it
          },
        },
      },
    }
  },
})
